name: Update external footer
on:
  schedule:
    - cron: "17 7 * * *"   # Daily at 07:17 UTC (change as you like)
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }
      - run: npm ci
      - run: npm run pull:footer
      - name: Commit & push if changed
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/ext/footer.html
            git commit -m "chore: refresh external footer"
            git push
          else
            echo "No changes"
          fi
